name: Waka Readme

on:
  schedule:
    # “At 00:01 on every day-of-week.”
    - cron: 0 1 * * *
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: false
          SHOW_OS: false
          SHOW_PROJECTS: true
          SHOW_TIMEZONE: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
